// Mocks generated by Mockito 5.4.6 from annotations
// in bizagent/test/features/tools/screens/ico_lookup_simulation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bizagent/core/models/ico_lookup_result.dart' as _i4;
import 'package:bizagent/features/tools/services/company_repository.dart'
    as _i2;
import 'package:bizagent/features/tools/services/watched_companies_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CompanyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyRepository extends _i1.Mock implements _i2.CompanyRepository {
  @override
  _i3.Future<_i4.IcoLookupResult?> getFromCache(String? ico) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFromCache,
          [ico],
        ),
        returnValue: _i3.Future<_i4.IcoLookupResult?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.IcoLookupResult?>.value(),
      ) as _i3.Future<_i4.IcoLookupResult?>);

  @override
  _i3.Future<_i4.IcoLookupResult?> refresh(
    String? ico, {
    String? existingHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [ico],
          {#existingHash: existingHash},
        ),
        returnValue: _i3.Future<_i4.IcoLookupResult?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.IcoLookupResult?>.value(),
      ) as _i3.Future<_i4.IcoLookupResult?>);

  @override
  _i3.Future<void> markAsOpened(
    String? uid,
    String? ico,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsOpened,
          [
            uid,
            ico,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [WatchedCompaniesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchedCompaniesService extends _i1.Mock
    implements _i5.WatchedCompaniesService {
  @override
  _i3.Future<void> watch(
    String? icoNorm,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [
            icoNorm,
            name,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unwatch(String? icoNorm) => (super.noSuchMethod(
        Invocation.method(
          #unwatch,
          [icoNorm],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<bool> isWatched(String? icoNorm) => (super.noSuchMethod(
        Invocation.method(
          #isWatched,
          [icoNorm],
        ),
        returnValue: _i3.Stream<bool>.empty(),
        returnValueForMissingStub: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Future<int> getWatchedCount() => (super.noSuchMethod(
        Invocation.method(
          #getWatchedCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> listWatched() => (super.noSuchMethod(
        Invocation.method(
          #listWatched,
          [],
        ),
        returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i3.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i3.Stream<List<Map<String, dynamic>>>);
}
