// Mocks generated by Mockito 5.4.6 from annotations
// in bizagent/test/features/ai/enhanced_ai_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bizagent/core/services/gemini_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i2.GeminiService {
  @override
  _i3.Future<String> generateContent(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #generateContent,
          [prompt],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateContent,
            [prompt],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateContent,
            [prompt],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  void addToConversation(
    String? conversationId,
    String? userMessage,
    String? aiResponse,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addToConversation,
          [
            conversationId,
            userMessage,
            aiResponse,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, String>> getConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversation,
          [conversationId],
        ),
        returnValue: <Map<String, String>>[],
        returnValueForMissingStub: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  _i3.Future<String> generateWithContext(
    String? conversationId,
    String? userMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateWithContext,
          [
            conversationId,
            userMessage,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateWithContext,
            [
              conversationId,
              userMessage,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateWithContext,
            [
              conversationId,
              userMessage,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> analyzeJson(
    String? context,
    String? schema,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeJson,
          [
            context,
            schema,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #analyzeJson,
            [
              context,
              schema,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #analyzeJson,
            [
              context,
              schema,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<String> generateContentStream(String? prompt) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateContentStream,
          [prompt],
        ),
        returnValue: _i3.Stream<String>.empty(),
        returnValueForMissingStub: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<Map<String, dynamic>> analyzeReceiptImage(dynamic imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeReceiptImage,
          [imageFile],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> generateText(String? prompt) => (super.noSuchMethod(
        Invocation.method(
          #generateText,
          [prompt],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateText,
            [prompt],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateText,
            [prompt],
          ),
        )),
      ) as _i3.Future<String>);
}
