// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'Platform ${defaultTargetPlatform} is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjWn54uyCL6YBtsqPCkWpatrwy306rZM',
    appId: '1:542280140779:android:4c205b8194929083373bae',
    messagingSenderId: '542280140779',
    projectId: 'bizagent-live-2026',
    storageBucket: 'bizagent-live-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8SnnqrxMkJPpKNcZ04v7hKBs-mLN3wM',
    appId: '1:542280140779:ios:5536609225fab278373bae',
    messagingSenderId: '542280140779',
    projectId: 'bizagent-live-2026',
    storageBucket: 'bizagent-live-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1M-oliyZ2ST3hqD8tWJR6oVisFKqlN-0',
    appId: '1:154036412101:web:76f6a60e2de27277381aac',
    messagingSenderId: '154036412101',
    projectId: 'bizagent-pro-2026',
    authDomain: 'bizagent-pro-2026.firebaseapp.com',
    storageBucket: 'bizagent-pro-2026.firebasestorage.app',
  );
}
