// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android is not supported for this project.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not supported for this project.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported for this project.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported for this project.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported for this project.',
        );
      default:
        return web; // Fallback for web
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1M-oliyZ2ST3hqD8tWJR6oVisFKqlN-0',
    appId: '1:154036412101:web:76f6a60e2de27277381aac',
    messagingSenderId: '154036412101',
    projectId: 'bizagent-pro-2026',
    authDomain: 'bizagent-pro-2026.firebaseapp.com',
    storageBucket: 'bizagent-pro-2026.firebasestorage.app',
  );
}