// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Mobile/Desktop platforms removed for web-only focus
    throw UnsupportedError(
      'Platform ${defaultTargetPlatform} is not supported for this web project.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcQ0RbF69p_uA1irgr7-hDkZPF95nSAQ',
    appId: '1:542280140779:web:572f4edccd696c9f373bae',
    messagingSenderId: '542280140779',
    projectId: 'bizagent-live-2026',
    authDomain: 'bizagent-live-2026.firebaseapp.com',
    storageBucket: 'bizagent-live-2026.firebasestorage.app',
  );
}