// Mocks generated by Mockito 5.4.6 from annotations
// in bizagent/test/features/ai_tools/screens/biz_bot_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:bizagent/core/services/enhanced_ai_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EnhancedAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedAIService extends _i1.Mock implements _i2.EnhancedAIService {
  @override
  _i3.Future<String> askBizBot(
    String? query, {
    List<Map<String, dynamic>>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #askBizBot,
          [query],
          {#context: context},
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #askBizBot,
            [query],
            {#context: context},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #askBizBot,
            [query],
            {#context: context},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> analyzeReceipt(_i4.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeReceipt,
          [imageFile],
        ),
        returnValue: _i3.Future<Map<String, dynamic>>.value(
            <String, dynamic>{}),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
            <String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> generateRevenueForecast(
          List<dynamic>? historicalData) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRevenueForecast,
          [historicalData],
        ),
        returnValue: _i3.Future<Map<String, dynamic>>.value(
            <String, dynamic>{}),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
            <String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
