// Mocks generated by Mockito 5.4.6 from annotations
// in bizagent/test/features/ai_tools/screens/biz_bot_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bizagent/features/ai_tools/services/biz_bot_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BizBotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBizBotService extends _i1.Mock implements _i2.BizBotService {
  @override
  _i3.Future<String> ask(String? question) => (super.noSuchMethod(
        Invocation.method(
          #ask,
          [question],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #ask,
            [question],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #ask,
            [question],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<String> askStream(String? question) => (super.noSuchMethod(
        Invocation.method(
          #askStream,
          [question],
        ),
        returnValue: _i3.Stream<String>.empty(),
        returnValueForMissingStub: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<void> softDeleteConversation({String? reason}) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteConversation,
          [],
          {#reason: reason},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> restoreConversation() => (super.noSuchMethod(
        Invocation.method(
          #restoreConversation,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> analyzeNote(String? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeNote,
          [content],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}
